### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by lichengwu** [lee-dohm/set-syntax#5]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
createCommand (/Users/lichengwu/.atom/packages/set-syntax/lib/main.coffee:16:9)
```

**Comment by lee-dohm** [comment]
Are you using v0.2.0 of `set-syntax`? The latest version doesn't call `atom.workspaceView`.

**Comment by lee-dohm** [comment]
I can't reproduce this. Let me know if you're on v0.2.0 and you can still reproduce it. Thanks!
